# .github/workflows/test.yml
name: Tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
    - uses: dschep/install-poetry-action@v1.3
      with: 
        version: 1.0.5
    - run: poetry install
    - run: nox
